[package]
name = "mspview"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colours = "0.1.1"
eframe = "0.22.0"
futures = "0.3.28"
image = "0.24.6"
json = "0.12.4"
paho-mqtt = "0.12.1"
